### ISSUE TITLE
EditorWindow 개선.(섹션을 rect로 나누지 말고 다른 방식으로 나누기. )

### ISSUE THREAD

**Issue by hongsam14** [hongsam14/myCPU#18]

**Comment by hongsam14** [comment]
flexible space를 활용하여 작업하고자 합니다.

**Comment by hongsam14** [comment]
https://docs.unity3d.com/kr/2017.4/Manual/gui-Layout.html
이것을 보고 제가 고정 레이아웃(rect)와 자동레이아웃을 혼용하고 있다는 것을 알았습니다. 고로 flexible space를 활용하지 않아도 여러 계층의 수직/수평 그룹을 만들어 의도한 window를 그릴 수 있었습니다.

**Comment by jongfeel** [comment]
음 저한테 보고(?) 하듯이 안하셔도 됩니다.

개인적으로 한 것 처럼 하셔도 되요. 아니 그렇게 하셔야 합니다!

**Comment by hongsam14** [comment]
넵ㅋㅋ 어쩌다보니 어조가 그렇게 되었네요
