### ISSUE TITLE
03/14 Xor Gate prefab 만들기.

### ISSUE THREAD

**Issue by hongsam14** [hongsam14/myCPU#44]
예상보다 학교 과제가 늦게 끝나 23시에 작업을 시작하게 되었다. 하지만 어제 여러개의 wire를 긋는데에 성공하였기 때문에, 이제 게이트 프리팹을 만드는 데에는 많은 시간이 걸릴 것 같지 않다. 

- [x] Xor Gate prefab 만들기.

**Comment by hongsam14** [comment]
예상 시간보다 늦게 작업을 시작하는 경우가 많아지고 있다. 하지만 하루에 두시간씩의 작업 시간을 가지려고 노력하고 있다.

**Comment by hongsam14** [comment]
알고보니 급한 과제가 하나 더 있었다. 지금 못한 것은 오늘 오후에 작업해야 할 것 같다...

**Comment by jongfeel** [comment]
음... 시작 시간과 종료 시간을 꼭 지켜야 한다 까지는 아니고요
몇 시간을 작업할 수 있는지를 정하고 자유롭게 그 시간만큼을 투자하자 이런 얘기입니다.
너무 부담 안가지셔도 되요

**Comment by hongsam14** [comment]
지키려고 노력중이긴 한데 부담은 아닙니다 ㅋㅋ
