### ISSUE TITLE
이번 주 작업 내용하고 진행 사항 공유

### ISSUE THREAD

**Issue by jongfeel** [hongsam14/myCPU#5]
이번주는 조금 다른 일로 바쁘신거 같은데
진행상황 공유를 할 수 있을까요?

**Comment by hongsam14** [comment]
네 본과정 과제를 진행하느라 시간 할당을 많이 못했습니다. (월말 지원금 때문에...)
기존 코드에서 InPort 와 outPort 코드를 제거하고 간단한 게이트 관련 코드만 남기려고 했습니다만, 생각해볼 점이 몇개 있어서 그 부분을 처리하고 있습니다. (wiki)에 정리해두었습니다. 멀티 플렉서와 기본게이트들, 다중게이트까지 구현하려고 합니다.

**Comment by jongfeel** [comment]
https://github.com/hongsam14/myCPU/wiki/Week_3:-basic-gate-prefabs

내용이 생각보다 많아서 놀랐습니다.

이번주 쯤에 pull reqeust 코드 리뷰를 해보면 좋겠다고 생각했는데,
오늘 제가 한번 설명해 드리면 좋을 것 같다는 생각도 드네요.
